### ISSUE TITLE
create in-memory authentication for testing purposes

### ISSUE THREAD

**Issue by jmorwick** [mwsu-csmp/gg-server#2]
include two fake user accounts

see example here https://github.com/jmorwick/codecafe/blob/master/src/main/java/net/sourcedestination/codecafe/networking/CodeCafeSecurity.java

**Comment by wwesp** [comment]
3e284b07d1f80313dc6cdda275b2e075ec5f29ba
log in added to the game
user, password
user2, password
user3, password
